### ISSUE TITLE
how do I run multiple samples?

### ISSUE THREAD

**Issue by kwanghoon821** [genepattern/MethylationCNVAnalysis#5]
Is there any way to run multiple samples?

I'm now just doing open each module, and upload each samples to them.

**Comment by bahill** [comment]
Hello, 
Within the GenePattern webapp (for instance on our Amazon hosted server - https://cloud.genepattern.org) you can [submit batch jobs via check box.](https://www.genepattern.org/user-guide#running-modules-and-pipelines-batch-processing)

If you are using a GenePattern Notebook you will need to write code for this batch submission.

All the best
-Barbara

**Comment by kwanghoon821** [comment]
Thank you!
